steps:
  # Secret Manager에서 비밀 정보 가져오기
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Secret Manager에서 JSON 키 파일 가져오기
        gcloud secrets versions access latest --secret=baking-buddy-key > resources/keys/cookingbunnies-8795bdb79870.json

  # Gradle 설치 및 빌드
  - name: 'gradle:7.5.1-jdk17'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        ./gradlew build --no-daemon
        # 필요한 경우 또는 빌드할 JAR 파일 이름이 다르면 설정
        cp build/libs/*.jar app.jar
    dir: /workspace   # 작업 디렉토리 설정

  # Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'asia-northeast3-docker.pkg.dev/cookingbunnies/baking-buddy-image'
      - '--build-arg=JAR_FILE=app.jar'  # 빌드할 JAR 파일 경로 지정
      - '.'
    dir: /workspace   # 작업 디렉토리 설정

  # Artifact Registry에 이미지 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'asia-northeast3-docker.pkg.dev/cookingbunnies/baking-buddy-image'
    dir: /workspace   # 작업 디렉토리 설정

options:
  logging: CLOUD_LOGGING_ONLY

secrets:
  - kmsKeyName: projects/cookingbunnies/locations/global/keyRings/my-key-ring/cryptoKeys/my-key
    secretEnv:
      BAKING_BUDDY_KEY: projects/cookingbunnies/secrets/baking-buddy-key/versions/latest