version: '3.8'

services:
  app:
    image: baking-buddy-image
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://baking-buddy-428009:asia-northeast3:baking-buddy-sql
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_REDIS_HOST: 10.170.239.131
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: baking_buddy
  redis:
    image: redis:latest
    ports:
      - "6379:6379"