version: '3.8'

services:
  app:
    image: baking-buddy-image
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://cookingbunnies:asia-northeast3:cooking-bunnies-db/cooking-bunnies-db
      SPRING_DATASOURCE_USERNAME: yooyeon
      SPRING_DATASOURCE_PASSWORD: yooyeon
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
    depends_on:
      - db
      - redis

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cooking-bunnies-db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
