server:
  port: 8080
  servlet:
    session:
      cookie:
        same-site: "None"
        secure: true

spring:
  profiles:
    active: mysql
  data:
    redis:
      host: 10.62.178.147
      port: 6379
    jedis:
      pool:
        max-wait-millis: 1000
    serialization:
      value: jdk
  mvc:
    charset: UTF-8

  application:
    name: BakingBuddy

  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://127.0.0.1:3306/baking_buddy
    username: yooyeon
    password: yooyeon
#    password: root
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:~/baking_buddy
  #    username: sa


  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MBß

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:/keys/cookingbunnies-8795bdb79870.json
        project-id: cookingbunnies
        bucket: cooking-bunnies
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
jwt:
  secret: 7JWI64WV7ZWY7IS47JqULiDtmansnKDsl7DsnoXri4jri6QuIOyggOuKlCDrsqDsnbTtgrkg67KE65SU66W8IOunjOuToCDqsJzrsJzsnpAg7J6F64uI64ukLg==
  refresh-expiration: 2592000000 # 30일
  access-expiration: 3600000 # 1시간

logging:
  level:
    org:
      springframework:
        security: INFO
        web: INFO
      hibernate: INFO


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans
      base-path: "/manage"

