spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1000199336931-ttf2apdad8hk3fs0m932qhkmt5ehmvc3.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: /login/oauth2/code/google
            scope:
              - email
              - profile
      provider:
        google:
          authorization-uri: https://accounts.google.com/o/oauth2/auth
          token-uri: https://oauth2.googleapis.com/token
          user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
          user-name-attribute: sub

  data:
    redis:
      host: 127.0.0.1
      port: 6379
    jedis:
      pool:
        max-wait-millis: 1000
    serialization:
      value: jdk
  mvc:
    charset: UTF-8

  application:
    name: BakingBuddy

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/baking_buddy
    username: root
    password: root
  #    driver-class-name: org.h2.Driver
  #    url: jdbc:h2:~/baking_buddy
  #    username: sa


  jpa:
    #    database-platform: org.hibernate.dialect.H2Dialect
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  #        dialect: org.hibernate.dialect.H2Dialect

  #  servlet:
  #    multipart:
  #      max-file-size: 10MB
  #      max-request-size: 10MB

  cloud:
    gcp:
      storage:
        credentials:
          location: classpath:/keys/baking-buddy-428009-28b83cf67c33.json
        project-id: baking-buddy-428009
        bucket: baking-buddy-bucket
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
jwt:
  secret: 7JWI64WV7ZWY7IS47JqULiDtmansnKDsl7DsnoXri4jri6QuIOyggOuKlCDrsqDsnbTtgrkg67KE65SU66W8IOunjOuToCDqsJzrsJzsnpAg7J6F64uI64ukLg==
  refresh-expiration: 2592000000 # 30일
  access-expiration: 3600000 # 1시간

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG
      hibernate: DEBUG


management:
  endpoints:
    web:
      exposure:
        include: "*"
        exclude: env, beans
      base-path: "/manage"
server:
  port: 8080
