spring:
  profiles:
    active: mysql
  application:
    name: BakingBuddy
  sql:
    init:
      mode: always
  datasource:
    username: root
    password: root

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: update
#      connection:

    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html
logging:
  level:
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR